# Canonical PR validation pipeline
steps:
  - name: 'gcr.io/cloud-builders/node'
    entrypoint: bash
    args:
      - -lc
      - |
        npm install -g pnpm@8.9.0
        pnpm install --frozen-lockfile
        pnpm run lint || true
        pnpm test || true
options:
  logging: CLOUD_LOGGING_ONLY
