steps:
  - name: node:20
    entrypoint: bash
    args:
      - -lc
      - |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm run validate

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: bash
    args:
      - -lc
      - |
        chmod +x scripts/golden-check.sh
        bash scripts/golden-check.sh
