steps:
  # Install dependencies and run validation
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        npm install -g pnpm@8.9.0
        pnpm install
        pnpm run validate

  # Build Docker image to verify it builds correctly (without pushing)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/hathor-red:$COMMIT_SHA', '.']

options:
  logging: CLOUD_LOGGING_ONLY
