# Generic PR CI: run unit tests + lint. Customize commands to your stack.
# Trigger this on PRs targeting main.
steps:
  - name: "gcr.io/cloud-builders/git"
    entrypoint: "bash"
    args: ["-lc", "git --version && echo PR-CI"]
  - name: "node:20"
    entrypoint: "bash"
    args:
      - "-lc"
      - |
        set -euo pipefail
        echo "TODO: replace with your test runner"
        if [ -f package.json ]; then
          echo "Detected Node project; running npm ci + test"
          npm ci
          npm test
        elif [ -f pyproject.toml ] || [ -f requirements.txt ]; then
          echo "Detected Python project; running pytest (best-effort)"
          python -V || true
          pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest || true
          pytest -q
        else
          echo "No recognized test setup; add commands in cloudbuild/pr-ci.yaml"
        fi
options:
  logging: CLOUD_LOGGING_ONLY
