substitutions:
  _REGION: us-central1
  _SERVICE: hather-red
  _AR_REPO: containers
  _RUNTIME_SA: hather-red-runtime

steps:
  - name: 'node:20'
    id: 'npm install'
    entrypoint: bash
    args: ['-c', 'set -euo pipefail; npm ci || npm install']

  - name: 'node:20'
    id: 'lint (if present)'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        node -e "process.exit(require('./package.json').scripts?.lint?0:1)" || exit 0
        npm run lint

  - name: 'node:20'
    id: 'test (if present)'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        node -e "process.exit(require('./package.json').scripts?.test?0:1)" || exit 0
        npm test

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker build'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker push'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'deploy cloud run'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--service-account'
      - '${_RUNTIME_SA}@$PROJECT_ID.iam.gserviceaccount.com'
      - '--set-env-vars'
      - 'NODE_ENV=production,PORT=8080'
      - '--allow-unauthenticated'

images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO}/${_SERVICE}:$COMMIT_SHA'
