steps:
  - name: 'node:20'
    id: 'install'
    entrypoint: bash
    args: ['-c', 'set -euo pipefail; npm ci || npm install']

  - name: 'node:20'
    id: 'lint (if present)'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        node -e "process.exit(require('./package.json').scripts?.lint?0:1)" || exit 0
        npm run lint

  - name: 'node:20'
    id: 'test (if present)'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        node -e "process.exit(require('./package.json').scripts?.test?0:1)" || exit 0
        npm test

  - name: 'node:20'
    id: 'build (if present)'
    entrypoint: bash
    args:
      - -c
      - |
        set -euo pipefail
        node -e "process.exit(require('./package.json').scripts?.build?0:1)" || exit 0
        npm run build
